require:
- rubocop-minitest
- rubocop-sketchup

# If you want to use the same codding pattern as SketchUp's projects, enable
# the next line. RuboCop will then use the coding pattern from the
# rubocop-sketchup project. This coding pattern is a more relaxed version than
# the default RuboCop pattern.
# inherit_from: https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/master/sketchup-style.yml

AllCops:
  # This prevents normal RuboCop cops to run. Disable this to get full static
  # analysis of your Ruby code.
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
  - src/*/vendor/**/* # Exclude skippy vendor folder
  - research/**/*
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2018
    Exclude: # Exclude common folders.
    - profiling/**/*
    - skippy/**/*
    - tests/**/*
  TargetRubyVersion: 2.7


# If DisabledByDefault is set to true then we need to enable the SketchUp
# related departments:

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true

SketchupBugs:
  Enabled: true


Lint/DeprecatedClassMethods:
  Enabled: true

SketchupPerformance/Typename:
  Exclude:
  - src/tt_transformation/nodes/node.rb
  - src/tt_transformation/node_editor.rb
